import datetime
from dateutil.tz import tzutc

test_dict = \
    {'api_version': 'v1',
     'items': [{'api_version': None,
                'kind': None,
                'metadata': {
                    'annotations': {u'kubeadm.alpha.kubernetes.io/cri-socket': '/var/run/dockershim.sock',
                                    u'node.alpha.kubernetes.io/ttl': '0',
                                    u'volumes.kubernetes.io/controller-managed-attach-detach': 'true'},
                    'cluster_name': None,
                    'creation_timestamp': datetime.datetime(2019, 8, 22, 8, 27, 15, tzinfo=tzutc()),
                    'deletion_grace_period_seconds': None,
                    'deletion_timestamp': None,
                    'finalizers': None,
                    'generate_name': None,
                    'generation': None,
                    'initializers': None,
                    'labels': {u'beta.kubernetes.io/arch': 'amd64',
                               u'beta.kubernetes.io/os': 'linux',
                               u'kubernetes.io/arch': 'amd64',
                               u'kubernetes.io/hostname': 'k8s-master1',
                               u'kubernetes.io/os': 'linux',
                               u'node-role.kubernetes.io/master': ''},
                    'managed_fields': None,
                    'name': 'k8s-master1',
                    'namespace': None,
                    'owner_references': None,
                    'resource_version': '889046',
                    'self_link': '/api/v1/nodes/k8s-master1',
                    'uid': 'a5f6ef8c-c4b6-11e9-ba0e-fa163ec525f6'},
                'spec': {'config_source': None,
                         'external_id': None,
                         'pod_cidr': '10.233.64.0/24',
                         'provider_id': None,
                         'taints': [{'effect': 'NoSchedule',
                                     'key': 'node-role.kubernetes.io/master',
                                     'time_added': None,
                                     'value': None}],
                         'unschedulable': None},
                'status': {'addresses': [{'address': '192.168.100.40',
                                          'type': 'InternalIP'},
                                         {'address': 'k8s-master1',
                                          'type': 'Hostname'}],
                           'allocatable': {u'cpu': '1800m',
                                           u'ephemeral-storage': '17951112777',
                                           u'hugepages-1Gi': '0',
                                           u'hugepages-2Mi': '0',
                                           u'memory': '1445872Ki',
                                           u'pods': '110'},
                           'capacity': {u'cpu': '2',
                                        u'ephemeral-storage': '19478204Ki',
                                        u'hugepages-1Gi': '0',
                                        u'hugepages-2Mi': '0',
                                        u'memory': '2048272Ki',
                                        u'pods': '110'},
                           'conditions': [{'last_heartbeat_time': datetime.datetime(2019, 8, 29, 6, 26, 50,
                                                                                    tzinfo=tzutc()),
                                           'last_transition_time': datetime.datetime(2019, 8, 22, 8, 27, 9,
                                                                                     tzinfo=tzutc()),
                                           'message': 'kubelet has sufficient memory available',
                                           'reason': 'KubeletHasSufficientMemory',
                                           'status': 'False',
                                           'type': 'MemoryPressure'},
                                          ],
                           'config': None,
                           'daemon_endpoints': {'kubelet_endpoint': {'port': 10250}},
                           'images': [{'names': [
                               'docker.cloudin.cn:5000/kube-apiserver@sha256:ebfb9018e345697e85d7adc4664c9340570bca33fff126e158264a791c6a5708',
                               'docker.cloudin.cn:5000/kube-apiserver:v1.14.0'],
                               'size_bytes': 209787945},
                               ],
                           'node_info': {'architecture': 'amd64',
                                         'boot_id': '41bd8e0b-b035-44da-aed8-f0303c7fd99d',
                                         'container_runtime_version': 'docker://18.6.2',
                                         'kernel_version': '4.4.0-31-generic',
                                         'kube_proxy_version': 'v1.14.0',
                                         'kubelet_version': 'v1.14.0',
                                         'machine_id': '5e39e59027e547dd8caabc916591a550',
                                         'operating_system': 'linux',
                                         'os_image': 'Ubuntu 16.04 LTS',
                                         'system_uuid': '5E39E590-27E5-47DD-8CAA-BC916591A550'},
                           'phase': None,
                           'volumes_attached': None,
                           'volumes_in_use': None}},
               ],
     'kind': 'NodeList',
     'metadata': {'_continue': None,
                  'resource_version': '889127',
                  'self_link': '/api/v1/nodes'}}
